-- Deployment-owned OAuth client; public metadata only. / 部署所有的 OAuth 客户端，仅含公开元数据。
-- Apply as a reviewed forward-only D1 migration, not as separate CLI statements. / 作为已评审的只向前 D1 migration 应用，不得逐条执行。
INSERT INTO oauth_clients(client_id,display_name,client_type,token_endpoint_auth_method,sector_identifier,subject_salt_revision,state,created_at,updated_at) VALUES('subscribe','moeSegFault Subscribe','confidential','private_key_jwt','subscribe.moesegfault.dev',1,'enabled',unixepoch(),unixepoch());
INSERT INTO oauth_redirect_uris(redirect_uri_id,client_id,redirect_uri,match_mode,created_at) VALUES('01a10a8f-53aa-71e9-b589-728e3747f3b3','subscribe','https://subscribe.moesegfault.dev/auth/callback','exact',unixepoch());
INSERT INTO oauth_post_logout_redirect_uris(post_logout_redirect_uri_id,client_id,redirect_uri,created_at) VALUES('01a10a8f-53aa-7639-a036-233a37c6bcb6','subscribe','https://subscribe.moesegfault.dev/auth/logout/callback',unixepoch());
INSERT INTO oauth_client_scopes(client_id,scope,granted_at) VALUES('subscribe','openid',unixepoch());
INSERT INTO oauth_client_scopes(client_id,scope,granted_at) VALUES('subscribe','profile',unixepoch());
INSERT INTO oauth_client_keys(client_id,kid,algorithm,public_jwk_json,created_at) VALUES('subscribe','subscribe-production-20261005','RS256','{"kty":"RSA","n":"j13G886quuVRO-RTnCkQnZhVmHx_0z1amiqZt0PHFBpokZD7h8cit0DVb1metm9wmmvGNqKcu9LWsm5ILo9xrqTGbuNMe1FIA4lyjyhUro5zIh_zufynkPsvjjtPgqr_RV2kTHkbTY7i2mSUjtq4vyN2wCbB6BkfNhl8XSAzSczlf9qjKv1HiiG76ZNU48ZiSZ71n4y_oEk9V4y3h0e4KZnFxikPAnGotO9eqg9imAVtbuh9t65-vjGxUz8TYwJyr7_NjMFZNfww3Pcp2gFrh45yz4NscVv0ake7xhLM8868zcas8MEYMKYsK_z3kmKraBCCvVIPFE8L7cX4r0fXQQ","e":"AQAB","alg":"RS256","use":"sig","kid":"subscribe-production-20261005"}',unixepoch());
INSERT INTO security_audit_events(audit_event_id,event_name,occurred_at,observed_at,client_id,outcome,correlation_id,policy_revision,context_json) VALUES('01a10a8f-53aa-7608-a808-6681f7d9a934','identity.oauth_client.created',unixepoch(),unixepoch(),'subscribe','success','01a10a8f-53aa-7608-a808-6681f7d9a934',1,json_object('client_id','subscribe'));
INSERT INTO audit_archive_outbox(audit_event_id,r2_object_key,next_attempt_at) VALUES('01a10a8f-53aa-7608-a808-6681f7d9a934',printf('security-audit/unix-day-%d/%s.json',CAST(unixepoch()/86400 AS INTEGER),'01a10a8f-53aa-7608-a808-6681f7d9a934'),unixepoch());
