-- Deployment-owned OAuth client; public metadata only. / 部署所有的 OAuth 客户端，仅含公开元数据。
-- Apply as a reviewed forward-only D1 migration, not as separate CLI statements. / 作为已评审的只向前 D1 migration 应用，不得逐条执行。
INSERT INTO oauth_clients(client_id,display_name,client_type,token_endpoint_auth_method,sector_identifier,subject_salt_revision,state,created_at,updated_at) VALUES('subscribe-staging','moeSegFault Subscribe','confidential','private_key_jwt','subscribe-staging.moesegfault.dev',1,'enabled',unixepoch(),unixepoch());
INSERT INTO oauth_redirect_uris(redirect_uri_id,client_id,redirect_uri,match_mode,created_at) VALUES('01a10796-561b-722e-ade6-0d901a0e9185','subscribe-staging','https://subscribe-staging.moesegfault.dev/auth/callback','exact',unixepoch());
INSERT INTO oauth_post_logout_redirect_uris(post_logout_redirect_uri_id,client_id,redirect_uri,created_at) VALUES('01a10796-561b-7589-b418-4244fa245519','subscribe-staging','https://subscribe-staging.moesegfault.dev/auth/logout/callback',unixepoch());
INSERT INTO oauth_client_scopes(client_id,scope,granted_at) VALUES('subscribe-staging','openid',unixepoch());
INSERT INTO oauth_client_scopes(client_id,scope,granted_at) VALUES('subscribe-staging','profile',unixepoch());
INSERT INTO oauth_client_keys(client_id,kid,algorithm,public_jwk_json,created_at) VALUES('subscribe-staging','subscribe-staging-20261004','RS256','{"kty":"RSA","n":"lONLgFX--OSXr3F5ZLfetK22FUohagYYngLYq_y8SpzW_oqDr-hunr2TU3SxRK0Sp82K5XnOiPYL1MHuk8MDL-K2OG_3V9tGDcnHyo64vRH9f5LbpsWvDeJKitnfADmSAmK4jVJEzD2DeRK5iqy8xeA7xRlGIKOPWDSacopXX9Dw9FSdZ9-6jVWzTLarkXO_UuKwAUKdf9eHGC-nfWZvgM7i39fnKBm1fY20re71FqcuORI2awR9rMfQF033bj-DENfDujrxlccYNM3Zpfy7DfekDRl1SqIbEBDXVj4a80DLTXvzrZShhg3Uz86grTImj_8U4NRttYPiHfA0Ni55RQ","e":"AQAB","alg":"RS256","use":"sig","kid":"subscribe-staging-20261004"}',unixepoch());
INSERT INTO security_audit_events(audit_event_id,event_name,occurred_at,observed_at,client_id,outcome,correlation_id,policy_revision,context_json) VALUES('01a10796-561b-7ed8-a8ad-b7f3a4b279ba','identity.oauth_client.created',unixepoch(),unixepoch(),'subscribe-staging','success','01a10796-561b-7ed8-a8ad-b7f3a4b279ba',1,json_object('client_id','subscribe-staging'));
INSERT INTO audit_archive_outbox(audit_event_id,r2_object_key,next_attempt_at) VALUES('01a10796-561b-7ed8-a8ad-b7f3a4b279ba',printf('security-audit/unix-day-%d/%s.json',CAST(unixepoch()/86400 AS INTEGER),'01a10796-561b-7ed8-a8ad-b7f3a4b279ba'),unixepoch());
