import { normalizeLocale } from "@moesegfault/frontend-shared";
import type { Locale } from "@moesegfault/frontend-shared";

export { normalizeLocale };
export type { Locale };

const messages = {
  "zh-CN": {
    account: "账号中心", overview: "总览", profile: "个人资料", security: "安全中心", sessions: "登录设备", apps: "已连接应用",
    hello: "欢迎回来", subtitle: "你的数字身份、联系方式与安全设置，都在这里。", editProfile: "编辑个人资料", securityScore: "安全状态",
    displayName: "显示名称", bio: "自我介绍", locale: "界面语言", timezone: "时区", save: "保存更改", saved: "已保存", avatar: "头像", upload: "上传新头像", remove: "移除",
    contacts: "联系方式", email: "邮箱", mobile: "手机", value: "地址或号码", add: "添加", verified: "已验证", pending: "待验证", primary: "主要", makePrimary: "设为主要", verify: "验证", verificationCode: "验证码", confirm: "确认", resendCode: "重新发送", verificationSent: "8 位验证码已发送，请查看接收验证码的位置。", verificationComplete: "联系方式验证成功。", verificationFailed: "验证码确认失败。", verificationSendFailed: "暂时无法发送验证码。",
    password: "密码", passkeys: "Passkey", recovery: "恢复代码", twoFactor: "两步验证", enabled: "已启用", disabled: "未启用", manageAtLogin: "前往登录服务管理",
    comingSoon: "准备中", devicesIntro: "查看登录过此账号的浏览器与设备。", current: "当前设备", revoke: "退出此设备", connectedIntro: "这些应用可以代表你访问已授权的数据。", permissions: "权限", disconnect: "撤销授权",
    noApps: "还没有连接任何应用。", noSessions: "没有其他活跃会话。", loading: "正在读取最新状态…", retry: "重试", signIn: "前往登录", signOut: "退出登录",
    appearance: "外观", light: "浅色", dark: "深色", system: "跟随系统", language: "语言", menu: "菜单", close: "关闭", danger: "需要留意", secure: "状态良好",
    inApp: "应用内浏览器可能无法完成 Passkey 操作；如遇问题，请复制链接并在系统浏览器打开。", copyLink: "复制链接", copied: "已复制", notSignedIn: "需要先登录", notSignedInBody: "账号中心没有检测到登录会话。",
    landingPageTitle: "账号中心", landingEyebrow: "MOESEGFAULT · ACCOUNT CENTER", landingTitle: "让你的数字身份，始终由你掌控", landingBody: "在一个清晰、安心的空间里维护个人资料、登录安全与应用授权。登录后，你可以随时查看和调整账号状态。", landingSignIn: "登录账号中心", landingCreateAccount: "创建账号", landingReassurance: "登录由 moeSegFault Login 安全处理", landingFeaturesEyebrow: "一个账号，清晰管理", landingFeaturesTitle: "重要设置，不再散落各处", landingProfileTitle: "塑造你的个人形象", landingProfileBody: "集中管理头像、显示名称、简介与联系方式，让每一次亮相都属于你。", landingSecurityTitle: "守护每一次登录", landingSecurityBody: "查看密码、Passkey 与活跃设备，及时发现并处理不熟悉的会话。", landingControlTitle: "掌握数据与授权", landingControlBody: "了解哪些应用可以访问你的资料，并在需要时随时撤销授权。",
    avatarTooLarge: "头像不得超过 10 MiB", avatarFormats: "支持 AVIF、PNG、JPEG、WebP，不超过 10 MiB；确认前会裁剪并优先压缩为 WebP（浏览器不支持时使用 PNG）", avatarPreparing: "正在裁剪并优化头像…", avatarPrepared: "头像已准备好，请确认后上传。", avatarConfirm: "确认上传", avatarCancel: "取消预览", avatarReselect: "重新选择", avatarInvalidType: "请选择 AVIF、PNG、JPEG 或 WebP 图片。", avatarEmpty: "所选图片为空，请重新选择。", avatarProcessingFailed: "无法处理这张图片，请换一张后重试。", statusMessage: "状态", pronouns: "称谓", favoriteCharacter: "最喜欢的角色", interests: "兴趣标签", links: "链接", visibility: "可见范围", private: "仅自己", members: "站内成员", public: "公开", countryRegion: "国家或地区", mainlandChina: "中国大陆", japan: "日本", singapore: "新加坡", usCanada: "美国或加拿大", unitedKingdom: "英国", hongKong: "中国香港", currentPassword: "当前密码", newPassword: "新密码", errorTitle: "页面暂时出了点小故障", unexpectedError: "发生了未知错误", federated: "联合登录", rename: "重命名", passkeyLabel: "Passkey 名称", technicalMethods: "TOTP 与 WebAuthn", reauthenticationBody: "这项操作需要先再次确认你的身份。完成登录后回到此页重试即可。", reauthenticate: "前往 Login 确认身份",
  },
  en: {
    account: "Account", overview: "Overview", profile: "Profile", security: "Security", sessions: "Sessions", apps: "Connected apps",
    hello: "Welcome back", subtitle: "Your identity, contacts, and security settings—all in one place.", editProfile: "Edit profile", securityScore: "Security status",
    displayName: "Display name", bio: "About you", locale: "Interface language", timezone: "Time zone", save: "Save changes", saved: "Saved", avatar: "Avatar", upload: "Upload new avatar", remove: "Remove",
    contacts: "Contact methods", email: "Email", mobile: "Mobile", value: "Address or number", add: "Add", verified: "Verified", pending: "Pending", primary: "Primary", makePrimary: "Make primary", verify: "Verify", verificationCode: "Verification code", confirm: "Confirm", resendCode: "Resend", verificationSent: "An 8-digit code was sent. Check the delivery destination.", verificationComplete: "Contact verified.", verificationFailed: "Could not confirm the code.", verificationSendFailed: "Could not send a verification code.",
    password: "Password", passkeys: "Passkeys", recovery: "Recovery codes", twoFactor: "Two-factor authentication", enabled: "Enabled", disabled: "Not enabled", manageAtLogin: "Manage at Login",
    comingSoon: "Coming soon", devicesIntro: "Review browsers and devices signed in to this account.", current: "This device", revoke: "Sign out device", connectedIntro: "These apps can access the data you approved.", permissions: "Permissions", disconnect: "Revoke access",
    noApps: "No connected apps yet.", noSessions: "No other active sessions.", loading: "Fetching the latest state…", retry: "Retry", signIn: "Go to Login", signOut: "Sign out",
    appearance: "Appearance", light: "Light", dark: "Dark", system: "System", language: "Language", menu: "Menu", close: "Close", danger: "Needs attention", secure: "Looking good",
    inApp: "Passkey actions may not work in an in-app browser. If needed, copy this link and open it in your system browser.", copyLink: "Copy link", copied: "Copied", notSignedIn: "Sign in required", notSignedInBody: "No sign-in session was found for the account center.",
    landingPageTitle: "Account Center", landingEyebrow: "MOESEGFAULT · ACCOUNT CENTER", landingTitle: "Your identity, always in your hands", landingBody: "A calm, clear home for your profile, sign-in security, and app permissions. Sign in to review and shape your account whenever you need.", landingSignIn: "Sign in to Account Center", landingCreateAccount: "Create account", landingReassurance: "Secure sign-in handled by moeSegFault Login", landingFeaturesEyebrow: "ONE ACCOUNT, CLEAR CONTROL", landingFeaturesTitle: "The important settings, all in one place", landingProfileTitle: "Make your profile yours", landingProfileBody: "Manage your avatar, display name, bio, and contact details so every appearance feels like you.", landingSecurityTitle: "Protect every sign-in", landingSecurityBody: "Review passwords, passkeys, and active devices, then deal with unfamiliar sessions quickly.", landingControlTitle: "Control data and access", landingControlBody: "See which apps can access your information and revoke their permissions whenever you choose.",
    avatarTooLarge: "Avatar must be 10 MiB or smaller", avatarFormats: "AVIF, PNG, JPEG or WebP, up to 10 MiB; cropped and compressed to WebP where supported (otherwise PNG) before confirmation", avatarPreparing: "Cropping and optimizing your avatar…", avatarPrepared: "Your avatar is ready. Confirm to upload it.", avatarConfirm: "Confirm upload", avatarCancel: "Cancel preview", avatarReselect: "Choose another", avatarInvalidType: "Choose an AVIF, PNG, JPEG, or WebP image.", avatarEmpty: "The selected image is empty. Choose another image.", avatarProcessingFailed: "This image could not be processed. Try another one.", statusMessage: "Status", pronouns: "Pronouns", favoriteCharacter: "Favorite character", interests: "Interests", links: "Links", visibility: "Visibility", private: "Only me", members: "Members", public: "Public", countryRegion: "Country or region", mainlandChina: "Mainland China", japan: "Japan", singapore: "Singapore", usCanada: "United States or Canada", unitedKingdom: "United Kingdom", hongKong: "Hong Kong", currentPassword: "Current password", newPassword: "New password", errorTitle: "This page had a tiny segfault", unexpectedError: "An unexpected error occurred", federated: "Federated sign-in", rename: "Rename", passkeyLabel: "Passkey label", technicalMethods: "TOTP and WebAuthn", reauthenticationBody: "Confirm your identity again before this action. Return here after signing in, then retry it.", reauthenticate: "Confirm at Login",
  },
  ja: {
    account: "アカウント", overview: "概要", profile: "プロフィール", security: "セキュリティ", sessions: "ログイン端末", apps: "連携アプリ",
    hello: "おかえりなさい", subtitle: "デジタル ID、連絡先、セキュリティ設定をひとつの場所で。", editProfile: "プロフィール編集", securityScore: "セキュリティ状態",
    displayName: "表示名", bio: "自己紹介", locale: "表示言語", timezone: "タイムゾーン", save: "変更を保存", saved: "保存しました", avatar: "アバター", upload: "新しい画像をアップロード", remove: "削除",
    contacts: "連絡先", email: "メール", mobile: "携帯電話", value: "アドレスまたは番号", add: "追加", verified: "確認済み", pending: "未確認", primary: "メイン", makePrimary: "メインにする", verify: "確認する", verificationCode: "確認コード", confirm: "確定", resendCode: "再送信", verificationSent: "8桁の確認コードを送信しました。送信先をご確認ください。", verificationComplete: "連絡先を確認しました。", verificationFailed: "コードを確認できませんでした。", verificationSendFailed: "確認コードを送信できませんでした。",
    password: "パスワード", passkeys: "パスキー", recovery: "リカバリーコード", twoFactor: "2段階認証", enabled: "有効", disabled: "無効", manageAtLogin: "Login で管理",
    comingSoon: "準備中", devicesIntro: "このアカウントにログイン中の端末を確認できます。", current: "この端末", revoke: "ログアウト", connectedIntro: "許可したデータにアクセスできるアプリです。", permissions: "権限", disconnect: "連携解除",
    noApps: "連携アプリはありません。", noSessions: "他のセッションはありません。", loading: "最新の状態を取得中…", retry: "再試行", signIn: "ログインへ", signOut: "ログアウト",
    appearance: "外観", light: "ライト", dark: "ダーク", system: "システム", language: "言語", menu: "メニュー", close: "閉じる", danger: "確認が必要", secure: "良好です",
    inApp: "アプリ内ブラウザではパスキー操作に失敗する場合があります。リンクをコピーしてシステムブラウザで開いてください。", copyLink: "リンクをコピー", copied: "コピーしました", notSignedIn: "ログインが必要です", notSignedInBody: "アカウントセンターのログインセッションが見つかりません。",
    landingPageTitle: "アカウントセンター", landingEyebrow: "MOESEGFAULT · ACCOUNT CENTER", landingTitle: "あなたのデジタル ID を、あなたの手に", landingBody: "プロフィール、ログインの安全性、アプリ権限を、見やすく安心できる場所で管理できます。ログインすれば、いつでもアカウントの状態を確認・調整できます。", landingSignIn: "アカウントセンターにログイン", landingCreateAccount: "アカウントを作成", landingReassurance: "安全なログインは moeSegFault Login が処理します", landingFeaturesEyebrow: "ひとつのアカウント、明快な管理", landingFeaturesTitle: "大切な設定を、ひとつの場所に", landingProfileTitle: "自分らしいプロフィール", landingProfileBody: "アバター、表示名、自己紹介、連絡先をまとめて管理し、自分らしさを表現できます。", landingSecurityTitle: "すべてのログインを守る", landingSecurityBody: "パスワード、パスキー、ログイン中の端末を確認し、心当たりのないセッションにすぐ対応できます。", landingControlTitle: "データと権限を管理", landingControlBody: "情報にアクセスできるアプリを確認し、必要に応じていつでも権限を取り消せます。",
    avatarTooLarge: "アバターは10 MiB以下にしてください", avatarFormats: "AVIF・PNG・JPEG・WebP、10 MiB以下。確認前に切り抜き、対応時は WebP、非対応時は PNG にします", avatarPreparing: "アバターを切り抜いて最適化しています…", avatarPrepared: "アバターの準備ができました。確認してアップロードしてください。", avatarConfirm: "アップロードを確定", avatarCancel: "プレビューを取消", avatarReselect: "別の画像を選ぶ", avatarInvalidType: "AVIF・PNG・JPEG・WebP 画像を選んでください。", avatarEmpty: "選択した画像は空です。別の画像を選んでください。", avatarProcessingFailed: "この画像を処理できませんでした。別の画像をお試しください。", statusMessage: "ステータス", pronouns: "代名詞", favoriteCharacter: "好きなキャラクター", interests: "興味タグ", links: "リンク", visibility: "公開範囲", private: "自分のみ", members: "メンバー", public: "公開", countryRegion: "国または地域", mainlandChina: "中国本土", japan: "日本", singapore: "シンガポール", usCanada: "米国またはカナダ", unitedKingdom: "英国", hongKong: "香港", currentPassword: "現在のパスワード", newPassword: "新しいパスワード", errorTitle: "ページで小さな不具合が発生しました", unexpectedError: "予期しないエラーが発生しました", federated: "連携ログイン", rename: "名前を変更", passkeyLabel: "パスキー名", technicalMethods: "TOTP と WebAuthn", reauthenticationBody: "この操作の前に、もう一度本人確認が必要です。ログイン後にこのページに戻り、再試行してください。", reauthenticate: "Login で本人確認",
  },
} as const;

export type MessageKey = keyof typeof messages["zh-CN"];

/** 创建无回退缺口的翻译函数。Creates a translation function with no missing-key fallback. */
export function translator(locale: Locale): (key: MessageKey) => string { return (key) => messages[locale][key]; }
